### ISSUE TITLE
Build Error TS5023 Unknown compiler option

### ISSUE THREAD

**Issue by pascalsz** [Breeze/temphire.angular2#1]
Hi Team,

i am trying to checkout the temphire angular implementation using a brand new Windows 10 Pro / Visual Studio Professional 2015 Update 3 / Node 4.5.0 Environment.

I followed your guide "Once everything is installed, in Visual Studio go to Tools|Options|Project and Solutions|External Web Tools and make sure Visual Studio is configured to use $(PATH) first to look for npm etc."

After a fresh checkout i receive the following error, when detailed debug output is activated.

C:\Repositories\GitHub\temphire.angular2\TempHire\error TS5023:Build:Unknown compiler option 'listemittedfiles'.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(214,5): error MSB6006: "tsc.exe" exited with code 1.

Any clou what i am missing ?

**Comment by pascalsz** [comment]
i also checked the path variables in windows and can confirm that tsc and npm are set.

in windows command prompt i checked the following:
npm -v
3.10.8
tsc -v
1.8.34

am i missing something else?

**Comment by marcelgood** [comment]
Sorry, I forgot to update the README. With the upgrade to ng2 final, you need to install TypeScript 2.0. I've add it to the prerequisites. 

https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/

**Comment by pascalsz** [comment]
Thanks. That solved my problems during the build.
