### ISSUE TITLE
Issue with adding new record to Staffresouce(Kindly provide the sample code)

### ISSUE THREAD

**Issue by rajsanil** [Breeze/temphire.angular2#6]

**Comment by rajsanil** [comment]
Kindly provide the code sample to add new record to staffresouce entity

**Comment by marcelgood** [comment]
Ok, I had some spare time on this rainy Saturday and I added the logic for adding a new StaffingResource. See the latest pushed code.

**Comment by rajsanil** [comment]
Sir, Error while adding new record An exception of type 'System.Exception' occurred in Breeze.ContextProvider.dll but was not handled in user code

Additional information: A foreign key value cannot be inserted because a corresponding primary key value does not exist. [ Foreign key constraint name = FK_dbo.Addresses_dbo.States_StateId ]

**Comment by marcelgood** [comment]
Yeah I think the validation isn't quite right. Just make sure you select a state.

**Comment by rajsanil** [comment]
Thank you sir
