### ISSUE TITLE
Gulp build errors

### ISSUE THREAD

**Issue by plwade** [Breeze/temphire.angular2#7]
I have cloned temphire from VS2015 (update 3), but I am unable to build the solution.
I'm getting the following gulp build errors:-
Error at C:/Users/Paul/Source/Repos/temphire.angular2/TempHire/node_modules/@types/jasmine/index.d.ts:39:38: A parameter initializer is only allowed in a function or constructor implementation.
Error at C:/Users/Paul/Source/Repos/temphire.angular2/TempHire/node_modules/@types/jasmine/index.d.ts:39:46: Cannot find name 'keyof'.
Error at C:/Users/Paul/Source/Repos/temphire.angular2/TempHire/node_modules/@types/jasmine/index.d.ts:39:52: '=' expected.

Here's a screenshot....
![capture](https://cloud.githubusercontent.com/assets/3742666/23141256/d33d8e8c-f7ad-11e6-9077-4ef931f90f2d.JPG)

Any help appreciated.

Regards, Paul

**Comment by marcelgood** [comment]
Thank you for letting me know. I just pushed a fix. I had to hardcode the `@types/jasmine` version to 2.5.41. The later versions are no longer compatible with TS 2.0. Unfortunately, this keeps happening until Google releases Angular 4, which will fully support TS 2.1. Currently the Angular AOT compiler is not compatible with TS 2.1, so I can't upgrade the sample yet. Get the latest and delete the `TempHIere/node_modules` folder before trying to build again. Make sure you close Visual Studio first.

**Comment by plwade** [comment]
Hi Marcel,

Thanks for the help.

Just to let you know..... I got the latest version from GitHub and deleted the node_modules folder and the build now works😊

I have been exploring the app and noticed there are no typescript (ts) files included when debugging in chrome dev tools.
I have checked that the tsconfig.json file has sourceMap set to ‘true’.
Any idea why I’m not seeing the ts files when debugging from chrome?

Any help appreciated.

Kind Regards,
Paul

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by marcelgood** [comment]
That's an artifact of using rollup.js to bundle the app. What you see in the Chrome debugger are the ES2015 modules generated from the TS files. The source map files map to the ES2015 modules which are the source for the rollup bundle. It doesn't look like rollup.js is the way forward for bundling Angular apps. This aspect of Angular along with AOT (ahead of time compilation) is still in flux. I will eventually convert it to what the Angular team will settle on. It might be Wepback 2, it might be something else. 

What you see in TempHire is an early take at bundling and AOT of an Angular app.

**Comment by plwade** [comment]
Thanks for the update Marcel. That explains why I can’t see ts files.

Regards,
Paul

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by plwade** [comment]
Hi Marcel,


I just wanted to thank you for your help and see if you could point me in the direction of an example of Breeze/Angular 2 being used in conjunction with IdentityServer4. I am interested in getting this working with Hybrid Flow and Refresh Tokens.


Any help appreciated.


Kind Regards,

Paul


________________________________
